name: Build
on: 
    push:
        branches: ["main"]
    schedule:
      - cron: "* */8 * * *" # Every 8 hours

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "trunk-based"
          main_branch_name: "main"

      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"

      - name: Run Terraform mirror 
        run: terraform providers mirror -platform=linux_amd64 ./plugins

      - name: Confirm plugins
        run: ls -R ./plugins

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build \
          --build-arg PROVIDERS=./plugins \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:${{ steps.semver-tag.outputs.semver_tag }} \
          . 

      - name: Publish image
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:latest


