name: Build
on: 
    push:
        branches: ["main"]
    #schedule:
    #  - cron: "* */8 * * *" # Every 8 hours

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Terraform mirror 
        run: terraform providers mirror -platform=linux_amd64 ./plugins

      - name: Confirm plugins
        run: ls ./plugins


      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:latest
      #    build-args: PROVIDERS="./plugins"

      - name: Build image
        run: docker build --build-arg PROVIDERS=./plugins -t ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:latest . 

      - name: Publish image
        run: docker push -t ${{ secrets.DOCKERHUB_USERNAME }}/terraform-agent:latest . 


