name: Build
on: 
    push:
        branches: ["main"]

jobs:
  fetch-plugins:
    name: Fetch Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Terraform mirror 
        run: terraform providers mirror -platform=linux_amd64 ./plugins
