name: Build
on: 
    push:
        branches: ["main"]
    schedule:
      - cron: "* */8 * * *" # Every 8 hours

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Terraform mirror 
        run: terraform providers mirror -platform=linux_amd64 ./plugins

      - name: Confirm plugins
        run: ls ./plugins

      - name: Build image
        run: docker build --build-arg PROVIDERS=./plugins -t terraform-agent:latest . 


